export const ProductsActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    UPDATE_SELECTED_PRODUCT: "UPDATE_SELECTED_PRODUCT",
    ADD_PRODUCT: "ADD_PRODUCT"
}